events{

}

http{
    upstream gateway{
        server gateway1:8000;
        server gateway2:8000;
        server gateway3:8000;
    }
    server{
        listen 80;
        location /{
            proxy_pass http://gateway;
        }
    }
}